SET PAGESIZE 9999;

clear screen

spool c:\temp\USER_privs.txt replace

SHOW USER

COLUMN USERNAME FORMAT A15
COLUMN PRIVILEGE FORMAT A27
COLUMN ADMIN_OPTION FORMAT A3

SELECT USERNAME, PRIVILEGE, ADMIN_OPTION FROM USER_SYS_PRIVS ORDER BY 2; 

COLUMN GRANTEE FORMAT A15
COLUMN TABLE_NAME FORMAT A30
COLUMN PRIVILEGE FORMAT A10
COLUMN GRANTABLE FORMAT A3

SELECT GRANTEE, TABLE_NAME, PRIVILEGE, GRANTABLE FROM USER_TAB_PRIVS ORDER BY 2, 3;

COLUMN USERNAME FORMAT A15
COLUMN GRANTED_ROLE FORMAT A27
COLUMN ADMIN_OPTION FORMAT A3

SELECT USERNAME, GRANTED_ROLE, ADMIN_OPTION FROM USER_ROLE_PRIVS ORDER BY 2;

spool off

host notepad C:\TEMP\USER_privs.txt
