// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mapcontrol1.h"

/////////////////////////////////////////////////////////////////////////////
// CMapcontrol1

IMPLEMENT_DYNCREATE(CMapcontrol1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMapcontrol1 properties

/////////////////////////////////////////////////////////////////////////////
// CMapcontrol1 operations
